### ISSUE TITLE
Fails to compile without specific environment vars

### ISSUE THREAD

**Issue by attackgoat** [meh/rust-ffmpeg-sys#27]
Hi - I'm new to rust just pulled this library into my Cargo.toml, but unfortunately the build fails:
$ cargo build --verbose
check.c:3:32: fatal error: libavutil/avutil.h: No such file or directory

I'm running a brand new Ubuntu 16.04 desktop with the usual developer tools installed.

Looking through the code I found the environment vars to set and came to this command line which produces a build:
$ **CARGO_FEATURE_BUILD**= **OUT_DIR**=target cargo build

Is there some rusty-reason why this should be clearer to me? Or could the build.rs code fallback to defaults if needed?
- Build w/ toolchain if not built
- Use rust target directory

Thanks for this amazing repository!!

**Comment by meh** [comment]
You need to installl the headers for ffmpeg too, not just the shared libraries, you don't need to touch any environment variables, they're automatically set from the headers by the build script.

The package names for that depend on your distro.

**Comment by attackgoat** [comment]
Why would I mix the randomly-versioned ffmpeg from my package manager with the ffmpeg source you're downloading in build.rs? Build.rs seems to do the job and produce good library/object files.

**Comment by meh** [comment]
The `build.rs` only fetches and builds the ffmpeg sources when you enable the `build` feature, otherwise all it does is check what various defines are in the headers, because the layout of structs and presence of functionality greatly varies depending on how the library was built, and that changes from distro to distro to local builds.

I'm not sure the `build` feature works currently, there were some issues in cargo that prevented it from working properly, so you need to install the right packages to get the appropriate headers.

**Comment by attackgoat** [comment]
I've got those packages installed, example libx264-dev. I misunderstood your ffmpeg comment; but the build works for me. This missing bits were of course to set the dependency features to at least build+avcodec.
